---
title: "R_code_Robustness_check"
output:
  pdf_document: default
  html_document: default
date: "2023-05-10"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Robustness check

# DATA Processing

## Read in data

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(quantmod)
library(readr)
TE <- read.csv("Data/TE_price.csv")
getSymbols("DEXTAUS", src="FRED", from="2000-01-01", to="2022-12-31")
getSymbols("^TWII", src="yahoo", from="2000-01-01", to="2022-12-31")
getSymbols("^GSPC", src="yahoo", from="2000-01-01", to="2022-12-31")

# Subset the data from 2000-01-01 to 2022-12-31
DEXTAUS <- DEXTAUS["2000-01-01/2022-12-31"]


DEXTAUS <- na.omit(DEXTAUS)
GSPC <- na.omit(GSPC)
TWII <- na.omit(TWII)

```

```{r}
TE$Date <- as.Date(TE$Date, format = "%m/%d/%Y")
TE <- TE[order(TE$Date),]
TE <- TE[TE$Date>= as.Date("2012-01-01") & TE$Date<= as.Date("2022-12-31"),]
TE <- as.xts(TE)
```

```{r}
logEX <- log(DEXTAUS)
dlogEX <- diff(logEX, lag=1, differences=1)
dlogEX <- na.omit(dlogEX)

logGSPC <- log(GSPC)
dlogGSPC <- diff(logGSPC, lag=1, differences=1)
dlogGSPC <- na.omit(dlogGSPC$GSPC.Close)

logTWII <- log(TWII)
dlogTWII <- diff(logTWII, lag=1, differences=1)
dlogTWII <- na.omit(dlogTWII$TWII.Close)

logTE <- log(TE)
dlogTE <- diff(logTE, lag = 1, differences = 1)
dlogTE <- na.omit(dlogTE)
```



```{r}
date_dlogGSPC <- index(dlogGSPC)
date_dlogTWII <- index(dlogTWII)
date_dlogEX <- index(dlogEX)
date_dlogTE <- index(dlogTE)

common_date_TWII_12 <- Reduce(intersect, list(date_dlogEX, date_dlogGSPC, date_dlogTWII, date_dlogTE)) |> as.Date()



dlogTWII_common_12 <- dlogTWII[common_date_TWII_12]
dlogGSPC_common_TWII_12 <- dlogGSPC[common_date_TWII_12]
x_TWII_12 <- dlogTWII_common_12-dlogGSPC_common_TWII_12
y_TWII_12 <- dlogEX[common_date_TWII_12]


dlogTWII_common_12 <- data.frame(dlogTWII_common_12)
dlogGSPC_common_TWII_12 <- data.frame(dlogGSPC_common_TWII_12)
x_TWII_12 <- data.frame(x_TWII_12)
y_TWII_12 <- data.frame(y_TWII_12)


training_y_TWII_12 <- head(y_TWII_12, -20)
training_x_TWII_12 <- head(x_TWII_12,-20)

TWII_train_df_12 <- data.frame(training_y_TWII_12, training_x_TWII_12)


testing_y_TWII_12 <- tail(y_TWII_12, 20)
testing_x_TWII_12 <- tail(x_TWII_12, 20)

TWII_test_df_12 <- data.frame(testing_y_TWII_12, testing_x_TWII_12)

```


```{r}
library(tidyverse)
library(lmtest)
library(sandwich)
N <- length(TWII_train_df_12$DEXTAUS)
m <- floor(0.75 * N^(1/3))
reg_TWII_12 <- lm(DEXTAUS~ TWII.Close, data = TWII_train_df_12)
cat("OLS with Heteroskedasticity and Autocorrelation (HAC) Robust S.E.\n")
hac_se_TWII_12 <- coeftest(reg_TWII_12, vcov=NeweyWest(reg_TWII_12, prewhite = F, adjust = T, lag=m-1))
hac_se_TWII_12
```

```{r}
library(forecast)
predict_TWII_12 <- predict(reg_TWII_12, newdata = TWII_test_df_12)

mean((predict_TWII_12-tail(testing_y_TWII_12$DEXTAUS, 20))^2)
```

```{r}
d_TWII_12 <- (testing_y_TWII_12$DEXTAUS)^2-(predict_TWII_12-tail(testing_y_TWII_12$DEXTAUS, 20))^2

d_df_12 <- data.frame(d_TWII_12)
```

```{r}
N <- length(d_TWII_12)
m <- floor(0.75 * N^(1/3))
reg_d_TWII_12 <- lm(d_TWII_12~1, data=d_df_12)
coeftest(reg_d_TWII_12, vcov=NeweyWest(reg_d_TWII_12, prewhite = F, adjust = T, lag = m-1))
```

